# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovpn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\novpn.proto\x12\x0covpn_package\"5\n\x0cListResponse\x12%\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x14.ovpn_package.Client\"\"\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xa7\x01\n\x04OVPN\x12\x39\n\x04list\x12\x13.ovpn_package.Empty\x1a\x1a.ovpn_package.ListResponse\"\x00\x12\x30\n\x06get_id\x12\x12.ovpn_package.Name\x1a\x10.ovpn_package.ID\"\x00\x12\x32\n\x08get_name\x12\x10.ovpn_package.ID\x1a\x12.ovpn_package.Name\"\x00\x42\x1f\n\x0fir.behaves.ovpnB\x04OVPNP\x01\xa2\x02\x03HLWb\x06proto3')



_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
_CLIENT = DESCRIPTOR.message_types_by_name['Client']
_NAME = DESCRIPTOR.message_types_by_name['Name']
_ID = DESCRIPTOR.message_types_by_name['ID']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'ovpn_pb2'
  # @@protoc_insertion_point(class_scope:ovpn_package.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

Client = _reflection.GeneratedProtocolMessageType('Client', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT,
  '__module__' : 'ovpn_pb2'
  # @@protoc_insertion_point(class_scope:ovpn_package.Client)
  })
_sym_db.RegisterMessage(Client)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'ovpn_pb2'
  # @@protoc_insertion_point(class_scope:ovpn_package.Name)
  })
_sym_db.RegisterMessage(Name)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'ovpn_pb2'
  # @@protoc_insertion_point(class_scope:ovpn_package.ID)
  })
_sym_db.RegisterMessage(ID)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ovpn_pb2'
  # @@protoc_insertion_point(class_scope:ovpn_package.Empty)
  })
_sym_db.RegisterMessage(Empty)

_OVPN = DESCRIPTOR.services_by_name['OVPN']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017ir.behaves.ovpnB\004OVPNP\001\242\002\003HLW'
  _LISTRESPONSE._serialized_start=28
  _LISTRESPONSE._serialized_end=81
  _CLIENT._serialized_start=83
  _CLIENT._serialized_end=117
  _NAME._serialized_start=119
  _NAME._serialized_end=139
  _ID._serialized_start=141
  _ID._serialized_end=157
  _EMPTY._serialized_start=159
  _EMPTY._serialized_end=166
  _OVPN._serialized_start=169
  _OVPN._serialized_end=336
# @@protoc_insertion_point(module_scope)
